### ISSUE TITLE
Can't install phobos on Windows with Blender

### ISSUE THREAD

**Issue by pavel-visionmap** [dfki-ric/phobos#172]
I am trying to follow instructions in https://github.com/dfki-ric/phobos/wiki/Installation on Windows and it does not look right.
Blender successfully installed.
The exact same version of python that blender uses
pip brought pyyaml successfully.
The phobos setup - okay, version 0.8, after asking what's blender's version (and I figured out that instead of 2.79b I had to write 2.79)

The addon is visible in Blender, but clicking on the checkbox results in "no module named 'yaml'". 
Same result I get when trying to run "import yaml" manually from Blender prompt, and of course the sys.path of my python3.5.3 installation and within blender shows completely different things.

My guess is that phobos setup was somehow supposed to copy the yaml installation into blender, as it did for the addon. What am I doing wrong?

**Comment by Amudtogal** [comment]
Hi Pavel,
let's get this fixed, shall we?
What is the `sys.path` of Blender and your system python?
Phobos just copies the relevant python scripts to the Blender addon folder. Yaml is not touched by this, but instead imported from the `python_dist_packages.conf` which are added to Blenders path when run.
What does the `python_dist_packages.conf` file contain in your case?

**Comment by pavel-visionmap** [comment]
Hi Simon,
Thanks for taking care of this and many many apologies for disappearing, I
have been doing other things lately. I will definitely try this again and
get back to you ASAP.


- Pavel

**Comment by Amudtogal** [comment]
I just came back to this issue. We released version 1.0.1 recently, which should have resolved most of the installation bugs. Could you check back on the issue and try to reproduce the error?

Also, the [wiki pages](https://github.com/dfki-ric/phobos/wiki/Installation) about the installation is quite extensive and should contain everything you need. The Blender preferences only provide a preset for the user interface, which we like, but is not necessary.

**Comment by pavel-visionmap** [comment]
Hi Simon,
Thank you very much for following up on this. Really, it's unprecedented
treatment of user feedback :)
I'd be happy to get back to using your tool ASAP, though I moved to doing
something else lately. I will test the version and let's be in touch.

thanks again,
Pavel

**Comment by Amudtogal** [comment]
Hi Pavel,
that would be really great! Looking forward to your report :)
Best,
Simon

**Comment by msunardi** [comment]
I had to modify the `setup.py` file [line 99](https://github.com/dfki-ric/phobos/blob/master/setup.py#L99) and change `'blender'` to '`blender.exe`' to get it to recognize the blender executable. 
However, it was still unable to perform the rest of the setup tasks of installing pip and yaml with the errors:

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

This is my Blender installation path on Windows (default path) `C:\Program Files\Blender Foundation\Blender`. Seems like Python's `os.system()` call on Windows doesn't handle the whitespaces in the path too well.

I had to go to the Blender Python executable directly, and call the install commands from there like this [[how-to-install-python-modules-in-blender](http://www.codeplastic.com/2019/03/12/how-to-install-python-modules-in-blender/)]

**Comment by Amudtogal** [comment]
I am sorry, somehow this update slipped through my mails...

Coming back to the Windows error, could you check the installation with the current master? I just pushed a fix...

**Comment by Amudtogal** [comment]
I assume this is fixed, otherwise reopen please.

**Comment by YoruCathy** [comment]
Hello guys, I met exactly the same issue when using Blender version 2.79b and Phobos 7b5432e5d0fda264d8823a532395806313aff9a7. My system is Windows10. Are there any solutions?

**Comment by malter** [comment]
Hey, I would recommend that you try out the branch blender2.9: https://github.com/dfki-ric/phobos/tree/blender2.9
The new installation method is documented in the Readme file of the branch and should work on all platforms in the same way and it should be compatible with new Blender versions. As soon as I find the time I will prepare the branch to become the new master version. While doing that we can also support a release version of Phobos.

**Comment by YoruCathy** [comment]
Thanks, it works!

**Comment by Spike87** [comment]
Hello, I tried installing the branch blender2.9 on Windows10 using Blender 2.79b without success (gives an error). Does it require exactly the 2.9 version? On the Blender website, I can find the 2.93 version, sponsored as LTE. Would that work? Thanks

**Comment by vintagefilmography** [comment]
I have not used Blender for a long while. It is still installed on my windows10 laptop and runs ok. The version is V2.8.

**Comment by malter** [comment]
Hey, using the newest Blender version should work. I tried today with Blender 3.2.1 and the master branch of phobos following the install instructions on the masters Readme. I will try to fix some other issues this week and then create a new release, which should clean up with this deprecated restriction to Blender 2.79b.

**Comment by Spike87** [comment]
Thank you very much for the quick reply. I installed v2.9 and works well. Not switching to Blender 3 at the moment.
